/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    officers: Officer;
    pages: Page;
    posts: Post;
    events: Event;
    newsletters: Newsletter;
    winners: Winner;
    'award-events': AwardEvent;
    reports: Report;
    jobs: Job;
    media: Media;
    gallery: Gallery;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    officers: OfficersSelect<false> | OfficersSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    posts: PostsSelect<false> | PostsSelect<true>;
    events: EventsSelect<false> | EventsSelect<true>;
    newsletters: NewslettersSelect<false> | NewslettersSelect<true>;
    winners: WinnersSelect<false> | WinnersSelect<true>;
    'award-events': AwardEventsSelect<false> | AwardEventsSelect<true>;
    reports: ReportsSelect<false> | ReportsSelect<true>;
    jobs: JobsSelect<false> | JobsSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    gallery: GallerySelect<false> | GallerySelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  /**
   * Display name shown on author bylines. Please fill this in for your own account.
   */
  name?: string | null;
  role: 'admin' | 'editor' | 'author';
  avatar?: (number | null) | Media;
  /**
   * Short bio shown on author pages.
   */
  bio?: string | null;
  /**
   * e.g. "Texas A&M University"
   */
  affiliation?: string | null;
  /**
   * Legacy WordPress author id; used for migration.
   */
  wpAuthorId?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Describe this image for screen readers and when the image fails to load. One short sentence.
   */
  alt: string;
  /**
   * Optional caption shown under the image on posts/pages.
   */
  caption?: string | null;
  /**
   * Photographer / source attribution, if applicable.
   */
  credit?: string | null;
  /**
   * Legacy WordPress attachment id; used for migration de-duplication.
   */
  wpAttachmentId?: string | null;
  /**
   * Original URL on aag-giss.org (for migration audit).
   */
  wpSourceUrl?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    hero?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "officers".
 */
export interface Officer {
  id: number;
  name: string;
  role:
    | 'chair'
    | 'vice-chair'
    | 'immediate-past-chair'
    | 'past-chair'
    | 'academic-director'
    | 'communication-director'
    | 'commercial-director'
    | 'government-director'
    | 'treasurer'
    | 'secretary'
    | 'student-rep'
    | 'board-member'
    | 'past-officer';
  photo?: (number | null) | Media;
  affiliation?: string | null;
  bio?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  email?: string | null;
  links?: {
    website?: string | null;
    twitter?: string | null;
    linkedin?: string | null;
    googleScholar?: string | null;
    orcid?: string | null;
  };
  termStart?: string | null;
  termEnd?: string | null;
  /**
   * Show on the current Officers page. Uncheck when term ends.
   */
  isCurrent?: boolean | null;
  sortOrder?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title: string;
  slug: string;
  heroImage?: (number | null) | Media;
  /**
   * Optional small line above the title.
   */
  subtitle?: string | null;
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  /**
   * Include this page in the main site navigation.
   */
  showInNav?: boolean | null;
  /**
   * Sort order in the nav (lower = earlier).
   */
  menuOrder?: number | null;
  /**
   * Optional: nest this page under another page.
   */
  parent?: (number | null) | Page;
  wpPageId?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts".
 */
export interface Post {
  id: number;
  title: string;
  /**
   * URL-friendly identifier, e.g. "student-honors-2026". Lowercase, hyphens, no spaces.
   */
  slug: string;
  category:
    | 'news'
    | 'award'
    | 'meeting'
    | 'event'
    | 'call-for-papers'
    | 'newsletter'
    | 'board-nomination'
    | 'jobs'
    | 'website-update';
  /**
   * Free-form tags. Keep short.
   */
  tags?:
    | {
        tag?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Short summary shown in post lists. If blank, derived from content.
   */
  excerpt?: string | null;
  featuredImage?: (number | null) | Media;
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  author: number | User;
  coAuthors?: (number | User)[] | null;
  publishedAt?: string | null;
  /**
   * Pin to the home page.
   */
  featured?: boolean | null;
  /**
   * Legacy WordPress post id.
   */
  wpPostId?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events".
 */
export interface Event {
  id: number;
  title: string;
  slug: string;
  eventType: 'aag-session' | 'business-meeting' | 'lecture' | 'competition' | 'reception' | 'webinar' | 'other';
  startDate: string;
  endDate?: string | null;
  /**
   * e.g. "Detroit, MI" or "Online"
   */
  location?: string | null;
  /**
   * e.g. "AAG Annual Meeting 2026", "Cobo Center, Room 310"
   */
  venue?: string | null;
  coverImage?: (number | null) | Media;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  speakers?:
    | {
        name: string;
        affiliation?: string | null;
        /**
         * e.g. "Keynote", "Panelist"
         */
        role?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Optional external registration link.
   */
  registrationUrl?: string | null;
  /**
   * Tie this event to an evergreen page (e.g. Tobler Lecture).
   */
  relatedPage?: (number | null) | Page;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "newsletters".
 */
export interface Newsletter {
  id: number;
  title: string;
  /**
   * e.g. "Vol. 1, Issue 1" or "2025-09"
   */
  issueNumber?: string | null;
  issueDate: string;
  /**
   * The PDF file. Uploaded to the Media library first.
   */
  pdf: number | Media;
  /**
   * Optional thumbnail for the newsletter archive.
   */
  cover?: (number | null) | Media;
  /**
   * One or two sentences of what this issue covers.
   */
  summary?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "winners".
 */
export interface Winner {
  id: number;
  award: 'student-honors' | 'aangeenbrug' | 'tobler-lecture';
  /**
   * The competition year (e.g. 2026). Used to group entries and pick the latest cohort to display.
   */
  year: number;
  position: 'first' | 'second' | 'third' | 'honorable-mention' | 'finalist' | 'recipient' | 'speaker';
  name: string;
  /**
   * University or institution at time of award.
   */
  affiliation?: string | null;
  /**
   * Student Honors: title of the submitted paper. Tobler: title of the distinguished lecture. Leave blank for Aangeenbrug.
   */
  paperTitle?: string | null;
  /**
   * Headshot of the winner/recipient/speaker.
   */
  photo?: (number | null) | Media;
  /**
   * Optional short bio line or citation text to display under the name.
   */
  notes?: string | null;
  /**
   * Within the same year+position, lower numbers appear first (use for ties, e.g. two people sharing 2nd place).
   */
  sortOrder?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "award-events".
 */
export interface AwardEvent {
  id: number;
  /**
   * Internal: computed label for admin list view.
   */
  displayLabel?: string | null;
  award: 'student-honors' | 'aangeenbrug' | 'tobler-lecture';
  year: number;
  /**
   * Event poster / flyer. Shown at full size on the left of the award page.
   */
  poster?: (number | null) | Media;
  /**
   * When the event takes place.
   */
  eventDate?: string | null;
  /**
   * e.g. "Imperial B, Ballroom Level, Hilton, Tower 1, 2, 3 (San Francisco, California)"
   */
  location?: string | null;
  /**
   * e.g. "Hybrid (In-person, Streamed, and Recorded)"
   */
  format?: string | null;
  /**
   * Optional external registration / session link.
   */
  registrationUrl?: string | null;
  /**
   * Sub-sessions (e.g. Paper Competition I, II). Each session has a time and a table of presenters.
   */
  sessions?:
    | {
        title: string;
        /**
         * e.g. "2:30 PM – 3:50 PM PST"
         */
        time?: string | null;
        presenters?:
          | {
              name: string;
              affiliation?: string | null;
              paperTitle?: string | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reports".
 */
export interface Report {
  id: number;
  title: string;
  year: number;
  kind: 'minutes' | 'presentation' | 'budget' | 'annual-report' | 'other';
  /**
   * The file to download (DOCX, PPTX, XLSX, PDF). Uploaded to the Media library.
   */
  file: number | Media;
  /**
   * Optional one-line description shown under the title on the reports page.
   */
  summary?: string | null;
  /**
   * Minutes default to officers-only since they often contain internal deliberations. Budgets, annual reports, and summaries can usually be public.
   */
  visibility: 'public' | 'officers';
  sortOrder?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "jobs".
 */
export interface Job {
  id: number;
  title: string;
  slug: string;
  organization: string;
  /**
   * e.g. "Toronto, ON" or "Remote"
   */
  location?: string | null;
  jobType?: ('tenure-track' | 'tenured' | 'lecturer' | 'postdoc' | 'phd' | 'industry' | 'other') | null;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Application deadline, if known.
   */
  deadline?: string | null;
  /**
   * External application link.
   */
  applicationUrl?: string | null;
  /**
   * Optional PDF flyer or full job ad.
   */
  pdf?: (number | null) | Media;
  postedAt: string;
  status: 'active' | 'closed' | 'archived';
  wpPostId?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "gallery".
 */
export interface Gallery {
  id: number;
  image: number | Media;
  /**
   * Short caption shown under the image in the public gallery.
   */
  caption?: string | null;
  /**
   * Optional grouping, e.g. "AAG 2025 Detroit", "Tobler Lecture 2024". Items without an album fall under "General".
   */
  album?: string | null;
  /**
   * Photo credit or source (optional).
   */
  credit?: string | null;
  /**
   * When this photo was taken (optional).
   */
  takenAt?: string | null;
  /**
   * Lower numbers appear first within an album.
   */
  sortOrder?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'officers';
        value: number | Officer;
      } | null)
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'posts';
        value: number | Post;
      } | null)
    | ({
        relationTo: 'events';
        value: number | Event;
      } | null)
    | ({
        relationTo: 'newsletters';
        value: number | Newsletter;
      } | null)
    | ({
        relationTo: 'winners';
        value: number | Winner;
      } | null)
    | ({
        relationTo: 'award-events';
        value: number | AwardEvent;
      } | null)
    | ({
        relationTo: 'reports';
        value: number | Report;
      } | null)
    | ({
        relationTo: 'jobs';
        value: number | Job;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'gallery';
        value: number | Gallery;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  avatar?: T;
  bio?: T;
  affiliation?: T;
  wpAuthorId?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "officers_select".
 */
export interface OfficersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  photo?: T;
  affiliation?: T;
  bio?: T;
  email?: T;
  links?:
    | T
    | {
        website?: T;
        twitter?: T;
        linkedin?: T;
        googleScholar?: T;
        orcid?: T;
      };
  termStart?: T;
  termEnd?: T;
  isCurrent?: T;
  sortOrder?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  heroImage?: T;
  subtitle?: T;
  content?: T;
  showInNav?: T;
  menuOrder?: T;
  parent?: T;
  wpPageId?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts_select".
 */
export interface PostsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  category?: T;
  tags?:
    | T
    | {
        tag?: T;
        id?: T;
      };
  excerpt?: T;
  featuredImage?: T;
  content?: T;
  author?: T;
  coAuthors?: T;
  publishedAt?: T;
  featured?: T;
  wpPostId?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events_select".
 */
export interface EventsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  eventType?: T;
  startDate?: T;
  endDate?: T;
  location?: T;
  venue?: T;
  coverImage?: T;
  description?: T;
  speakers?:
    | T
    | {
        name?: T;
        affiliation?: T;
        role?: T;
        id?: T;
      };
  registrationUrl?: T;
  relatedPage?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "newsletters_select".
 */
export interface NewslettersSelect<T extends boolean = true> {
  title?: T;
  issueNumber?: T;
  issueDate?: T;
  pdf?: T;
  cover?: T;
  summary?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "winners_select".
 */
export interface WinnersSelect<T extends boolean = true> {
  award?: T;
  year?: T;
  position?: T;
  name?: T;
  affiliation?: T;
  paperTitle?: T;
  photo?: T;
  notes?: T;
  sortOrder?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "award-events_select".
 */
export interface AwardEventsSelect<T extends boolean = true> {
  displayLabel?: T;
  award?: T;
  year?: T;
  poster?: T;
  eventDate?: T;
  location?: T;
  format?: T;
  registrationUrl?: T;
  sessions?:
    | T
    | {
        title?: T;
        time?: T;
        presenters?:
          | T
          | {
              name?: T;
              affiliation?: T;
              paperTitle?: T;
              id?: T;
            };
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reports_select".
 */
export interface ReportsSelect<T extends boolean = true> {
  title?: T;
  year?: T;
  kind?: T;
  file?: T;
  summary?: T;
  visibility?: T;
  sortOrder?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "jobs_select".
 */
export interface JobsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  organization?: T;
  location?: T;
  jobType?: T;
  description?: T;
  deadline?: T;
  applicationUrl?: T;
  pdf?: T;
  postedAt?: T;
  status?: T;
  wpPostId?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  credit?: T;
  wpAttachmentId?: T;
  wpSourceUrl?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        hero?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "gallery_select".
 */
export interface GallerySelect<T extends boolean = true> {
  image?: T;
  caption?: T;
  album?: T;
  credit?: T;
  takenAt?: T;
  sortOrder?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}